### ISSUE TITLE
Corepack is not recognized as an internal or external command

### ISSUE THREAD

**Issue by tuan-lm97** [nodejs/corepack#101]
`Node -v` give me that I have Nodejs v16.14.2.
As stated in the docs,
> Corepack is included by default with all Node.js installs

So that mean my environment should already have Corepack. But run `corepack enable` give me error it's not recognized as a command

**Comment by aduh95** [comment]
I guess the docs should be updated, Corepack is included in official Node.js installs, but if you are getting Node.js from somewhere else (e.g. APT, pacman), you might not get it. How did you install Node.js?

**Comment by tuan-lm97** [comment]
@aduh95 I installed Node by pnpm

**Comment by aduh95** [comment]
> @aduh95 I installed Node by pnpm

Can you elaborate on this? AFAIK pnpm does not offer to install Node.js on your system 🤔 Did you follow a link or use some commands that you can paste in here? That would help me understand where you're coming from.

**Comment by arcanis** [comment]
> AFAIK pnpm does not offer to install Node.js on your system 🤔

They do - one way to install pnpm is to use the prebuilt binary, which doubles as a kind of Node version manager ([doc](https://pnpm.io/cli/env)).

@tuan-lm97 Whether pnpm exposes the Corepack binaries is up to their project, I'd suggest you to open an issue on their repo.
