### ISSUE TITLE
pnpx breaks in corepack+pnpm v7

### ISSUE THREAD

**Issue by Jack-Works** [nodejs/corepack#102]
https://github.com/pnpm/pnpm/releases/tag/v7.0.0

> pnpx is now just an alias of pnpm dlx.

> If you want to just execute the command of a dependency, run pnpm <cmd>. For instance, pnpm eslint.

> If you want to install and execute, use pnpm dlx <pkg name>.

Now I cannot run a pnpx command inside an npm configured project even though it installs the package in the global.

I need it because I need to run the following command:

> pnpx -y npm@latest-6 install

Otherwise, npm v7+ will upgrade the lock file which is unwanted for projects that I cannot control.

I cannot use npx either because npx will always use the installed version of npm v8 and ignore the `latest-6` I specified.

![image](https://user-images.githubusercontent.com/5390719/166268164-bdeee791-0dcd-49b1-bc3e-6fe2d0729db0.png)

**Comment by merceyz** [comment]
We need to update https://github.com/nodejs/corepack/blob/5ff6e82028e58448ba5ba986854b61ecdc69885b/config.json#L32-L42 to include `pnpm dlx`, would you like to open a PR adding it?

Since the `packageManager` field is already set to `npm`, shouldn't you let Corepack handle it instead of invoking `pnpx`?
```sh
corepack enable npm
```

**Comment by ljharb** [comment]
`npx npm@6` works just fine in every project i've ran it in - there should be no need to use the tag (altho i'd also be surprised if it didn't work with the tag)

**Comment by Jack-Works** [comment]
![image](https://user-images.githubusercontent.com/5390719/166395710-004dffa6-2d00-4fb2-a359-d4bdf7b30253.png)

🤔 It does not work

**Comment by Jack-Works** [comment]
> Since the packageManager field is already set to npm, shouldn't you let Corepack handle it instead of invoking pnpx?

Oh, I didn't notice that. I thought there was some reason that npm isn't enabled by default.

**Comment by ljharb** [comment]
@Jack-Works that seems like either an npm bug, or maybe you have a registry set up that's not returning the proper version of npm.
