### ISSUE TITLE
Race condition when initializing

### ISSUE THREAD

**Issue by rightaway** [nodejs/corepack#110]
When you have different projects that run yarn for the first time at the same time, there's a race condition and some of them fail.

```
ENOTEMPTY: directory not empty, rename '/home/main/.node/corepack/corepack-22551-d0a7e4bc.02f3c' -> '/home/main/.node/corepack/yarn/3.2.1'
```

Corepack should handle initializing yarn from more than 1 project at the same time because it is common when setting up from scratch.

**Comment by merceyz** [comment]
Fixed in https://github.com/nodejs/corepack/pull/84

**Comment by merceyz** [comment]
The fix has been released but I don't have access to close this so cc @aduh95 or @arcanis
