### ISSUE TITLE
How can I detect if corepack is already enabled?

### ISSUE THREAD

**Issue by styfle** [nodejs/corepack#113]
If we were to programmatically enable corepack, we would want to disable after the work is complete.

However, if the user already had corepack enabled, then we wouldn't want to disable it.

Is there a way to get the current state to determine if its already enabled?

**Comment by arcanis** [comment]
Can you detail more the use case you have in mind?

**Comment by styfle** [comment]
Basically this PR:

- https://github.com/vercel/vercel/pull/7871

Since corepack is changing global bins, we don't want to run `corepack disable` if the user had already enabled it. We only want to disable if we were the ones to enable it, thus leaving the user's system in the original state when we're done.

**Comment by arcanis** [comment]
You can detect whether you're running within a Corepack context by checking if `COREPACK_ROOT` is set in the env, cf [here](https://github.com/nodejs/corepack#environment-variables).

That said, for your own use case, I wonder if perhaps the absolute no-risks option wouldn't be to just enable corepack in a temporary folder which you'd add to the `PATH` of your subshells, and just optionally cleanup at the end of the execution?

**Comment by styfle** [comment]
Yeah that sounds good, how would I do that? 🙂

**Comment by merceyz** [comment]
The `enable` command allows you to specify where it should install the binaries.
```sh
corepack enable --install-directory="/tmp/some-random-directory"
```
https://github.com/nodejs/corepack/tree/2b7180eff8635bc344fdde2c7d12ffa0eac14b49#corepack-enable--name
