### ISSUE TITLE
corepack cleanup cache

### ISSUE THREAD

**Issue by styfle** [nodejs/corepack#114]
> If the local project is configured for the package manager you're using, Corepack will silently download and cache the latest compatible version.

Does corepack provide any way to delete the cache?

The use case I'm thinking of is CI/CD where you want to set `COREPACK_HOME` to a cached directory. However, unlike `node_modules`, it doesn't seem like this directory is ever pruned or cleaned up since its shared between many projects.

On a local machine, its probably fine to just periodically delete it. But for CI/CD, the project is only ever using one version of a package manager so its safe to prune old or unused versions.

For perspective, pnpm versions released in the last 30 days (>=7.0.0) amount to 180 MB. I imagine this will reach GB very quickly.

I'm thinking this can be solved with a new command:

```sh
 # delete all except current version defined in package.json
corepack cache clean

# delete all versions that have not been invoked for 30 days
corepack cache clean --before 30d
```

**Comment by ST-DDT** [comment]
> I find corepack is storing cache at `~/.node/corepack`. Maybe you can delete them manually. ![image](https://user-images.githubusercontent.com/2476434/177776511-8f129d24-638a-4c0e-a548-2bbb386885d6.png)

Is there a variable or something that I can use to get the correct path for the current platform?

**Comment by SukkaW** [comment]
Now `corepack` is eating 190 MiB of my disk space (and it will continue getting bigger). Cache cleaning cache is becoming more and more important.

<img width="720" alt="image" src="https://github.com/nodejs/corepack/assets/40715044/3a859a65-5301-4b73-b602-eb8ed50f214a">

**Comment by styfle** [comment]
Its been about a year and I checked again just now:

```
$ du -sh ~/.cache/node/corepack

1.6G
```

**Comment by SukkaW** [comment]
> Now `corepack` is eating 190 MiB of my disk space. Cache cleaning is becoming more and more important.

It is definitely becoming worse:

<img width="457" alt="image" src="https://github.com/nodejs/corepack/assets/40715044/d2bbea7f-2297-4a0d-a22b-316fa3c344b1">

70 days and the folder size increased by 130 MiB.
