### ISSUE TITLE
Unable to upgrade pnpm to v7

### ISSUE THREAD

**Issue by theolavaux** [nodejs/corepack#131]
I have installed `pnpm@6.32.20` through Corepack but now, I'm unable to version bump to v7 successfully.
The installs seems ok but it's still using the old version. It's also the same whenever I spawn a new shell.
How could I fix this?

<img width="268" alt="CleanShot 2022-06-17 at 12 35 58@2x" src="https://user-images.githubusercontent.com/25274586/174282105-d4831abf-6c69-42d7-82b0-f81b18e8cebd.png">

**Comment by arcanis** [comment]
What do you get with `which pnpm`? Did you check whether it points to the Corepack binary?

**Comment by theolavaux** [comment]
❯ which pnpm
/usr/local/bin/pnpm

Do you I need an extra step to use Corepack binary by default ?

**Comment by arcanis** [comment]
It's currently enabled, so you have at minima to run `corepack enable`. If you already did, perhaps you accidentally overrode those binaries by running `npm i -g pnpm` or similar (in which case `corepack enable` will repair your setup).

**Comment by theolavaux** [comment]
I don't think I did install `pnpm` via `npm`. This is my output with `corepack enable`, still seems KO.

❯ corepack enable
❯ corepack prepare pnpm@7.2.1 --activate
Preparing pnpm@7.2.1 for immediate activation...
❯ pnpm -v
6.32.20

**Comment by theolavaux** [comment]
I found something interesting, `pnpm@7.2.1` is activated inside a regular terminal but not inside VSCode's integrated terminal.

**Comment by bhatvikrant** [comment]
Same with me

**Comment by renet** [comment]
Same for me. Thanks! I updated the version number in the `packageManager` property. What would be the proper way to fix this for future updates? Remove this prop from the package.json, or something else?
