### ISSUE TITLE
Documentation: add instructions to configure package.json with `"packageManager": "xyz"`

### ISSUE THREAD

**Issue by NiloCK** [nodejs/corepack#187]
Under `Usage`, several mentions are made to corepack checking whether the project is configured for a specific package manager, but no instructions are given for configuring a project for a specific package manager.

The [yvm deprecation notice](https://yvm.js.org/docs/overview) and its linked example were the first instruction I found.

**Comment by jakobbouchard** [comment]
It's especially annoying when the project uses pnpm, but hasn't specified it in `package.json` and corepack assumes the project uses yarn instead, if yarn is also enabled.

**Comment by merceyz** [comment]
> It's especially annoying when the project uses pnpm, but hasn't specified it in `package.json` and corepack assumes the project uses yarn instead, if yarn is also enabled.

Corepack doesn't assume anything, if you're seeing otherwise please open a bug report.
