### ISSUE TITLE
[Feature Request] Persist "corepack enable" across Node versions

### ISSUE THREAD

**Issue by noahnu** [nodejs/corepack#192]
I use [nvm](https://github.com/nvm-sh/nvm) to manage my Node versions. Whenever I install a new Node version with nvm, I need to repeat `corepack enable`. It'd be nice if there was an option to `corepack enable --global` to persist corepack settings independent of Node, so that I can choose to opt-out instead of opt-in.

**Comment by arcanis** [comment]
For now it's up to individual nvm-like tools. In the future we'd want Corepack to be enabled by default

**Comment by noahnu** [comment]
That's fair. I was debating between opening the issue here or in nvm. I'll open a dedicated issue there.

**Comment by styfle** [comment]
> In the future we'd want Corepack to be enabled by default

- Related issue #104
