### ISSUE TITLE
corepack hydrate fails if $HOME/.cache/node/corepack does not exist

### ISSUE THREAD

**Issue by Gamadril** [nodejs/corepack#198]
Platform: MacOS x64
NodeJS version: v16.18.0
Corepack version: 0.14.1

Steps to reproduce:
- download nodejs 16.18.0 dist (https://nodejs.org/dist/v16.18.0/) (darwin-x64 in my case)
- cd into it
- run "export PATH=./bin:$PATH" to override globally installed nodejs version
- run "corepack enable"
- run "corepack prepare yarn@3.2.4 -o"
- empty $HOME/.cache folder
- run "corepack hydrate corepack.tgz"

Result:
```
Hydrating yarn@3.2.4...
Cwd Error: ENOENT: Cannot cd into '/Users/xxx/.cache/node/corepack'
    at /Users/xxx/Downloads/node-v16.18.0 /lib/node_modules/corepack/dist/corepack.js:6725:12
    at FSReqCallback.oncomplete (node:fs:202:21)
```

If I manually create $HOME/.cache/node/corepack folder, the hydrate command works.

Expected:
corepack creates the folder structure automatically if it does not exist.

**Comment by aduh95** [comment]
Do you want to send a PR to fix that?

**Comment by Gamadril** [comment]
I will try, however I cannot event build it.
Followed the instruction from README:

```
    - Clone this repository
    - Run yarn build (no need for yarn install)
    - The dist/ directory now contains the corepack build and the shims
    - Call node ./dist/corepack --help and behold
```

Cloned the repo.
"yarn build" fails:
```
yarn run v1.22.19
$ rm -rf dist shims && webpack && ts-node ./mkshims.ts
/bin/sh: webpack: command not found
error Command failed with exit code 127.
```

run "yarn" to install dependencies first, "yarn build" still fails:

```
ERROR in /Users/xxx/Projects/node/corepack/sources/commands/Hydrate.ts
./sources/commands/Hydrate.ts 40:29-35
[tsl] ERROR in /Users/xxx/Projects/node/corepack/sources/commands/Hydrate.ts(40,30)
      TS2339: Property 'header' does not exist on type 'ReadEntry'.
ts-loader-default_06006a6d86bad3e7
 @ ./sources/main.ts 5:0-52 85:21-35
 @ ./sources/_entryPoint.ts 1:0-33 3:0-19 6:4-11

webpack 5.74.0 compiled with 1 error and 3 warnings in 8154 ms
error Command failed with exit code 1.
```

**Comment by aduh95** [comment]
We should update those instructions, `corepack yarn install` is in fact needed.

**Comment by aduh95** [comment]
I've opened https://github.com/nodejs/corepack/pull/199 the instructions. In the output you're sending, it shows that you are using `yarn v1.22.19`, you should use the version of Yarn described in the `package.json`: https://github.com/nodejs/corepack/blob/9a09dad35141795a18c0fe0fc2090e252132d1ab/package.json#L13

If you have Corepack on your machine, you can do `corepack yarn install`; if you don't have Corepack, you need to download that version from the Yarn website (e.g. `curl https://repo.yarnpkg.com/4.0.0-rc.15/packages/yarnpkg-cli/bin/yarn.js > yarn.js && node yarn.js install && node yarn.js build`).

**Comment by Gamadril** [comment]
Thanks, will try to make the build working. However the fix is quite simple so I tested it in the patched js file directly and created the pull request for the fix.
