### ISSUE TITLE
add option to excludes ./node_modules when excuting 'corepack enable npm'

### ISSUE THREAD

**Issue by Soombra** [nodejs/corepack#207]
we want to lock package manager in out project. so we run 'corepack enable & corepack enable npm' and add "packageManager":"pnpm@7.14.2" in package.json file.
but, if some third part library has set a npm-script like:  "postinstall": "npm run build", the installation will fail. 
in my option, we should just lock the package manager for our own resource code. so, is there a way to exclude the 'node_modules' dir ?

**Comment by arcanis** [comment]
Closing as duplicate with #57.

Generally, if a package lists `npm run` in its postinstall scripts, it's a real problem in the package that Corepack merely surfaces (calling the wrong package manager, even with "simple" commands like `run`, may not work in the best cases or silently corrupt the project in the worst).
