### ISSUE TITLE
Will corepack work on node 12.x?

### ISSUE THREAD

**Issue by 0xdevalias** [nodejs/corepack#240]
I know the latest version of `corepack` won't run on node `12.x`, and I realise that `12.x` is deprecated.. but I was wondering if there is a version of `corepack` that will run on it?

Trying to install the latest version gives this error:

```
⇒ npm install -g corepack
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'corepack@0.16.0',
npm WARN EBADENGINE   required: { node: '>=14.14.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.10', npm: '8.19.3' }
npm WARN EBADENGINE }

added 1 package, and audited 2 packages in 2s

found 0 vulnerabilities
```

**Comment by 0xdevalias** [comment]
It looks like `0.15.3` can be installed:

```
 ⇒ npm install -g corepack@0.15.3

changed 1 package, and audited 2 packages in 554ms

found 0 vulnerabilities
```

But then it just throws errors:

```
⇒ corepack -h
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'fs/promises'
Require stack:
- /Users/devalias/.nodenv/versions/12.22.10/lib/node_modules/corepack/dist/corepack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.fs/promises (/Users/devalias/.nodenv/versions/12.22.10/lib/node_modules/corepack/dist/corepack.js:16716:18)
    at __webpack_require__ (/Users/devalias/.nodenv/versions/12.22.10/lib/node_modules/corepack/dist/corepack.js:17137:42)
    at Module../sources/fsUtils.ts (/Users/devalias/.nodenv/versions/12.22.10/lib/node_modules/corepack/dist/corepack.js:16033:69)
    at __webpack_require__ (/Users/devalias/.nodenv/versions/12.22.10/lib/node_modules/corepack/dist/corepack.js:17137:42)
    at Module../sources/corepackUtils.ts (/Users/devalias/.nodenv/versions/12.22.10/lib/node_modules/corepack/dist/corepack.js:15738:66)
    at __webpack_require__ (/Users/devalias/.nodenv/versions/12.22.10/lib/node_modules/corepack/dist/corepack.js:17137:42) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/devalias/.nodenv/versions/12.22.10/lib/node_modules/corepack/dist/corepack.js'
  ]
}
```

**Comment by RDIL** [comment]
As you said yourself, Node.js v12 is deprecated and is no longer supported by corepack. Please migrate to a newer version of Node in order to use corepack. (and just because it's still getting security patches on newer versions, which keeps you safer!)

**Comment by aduh95** [comment]
As said in the above commend, adding support for Node.js 12.x is not a goal. Wether you can hack your way into making Corepack work there is a different question (that's certainly possible, but is it worth it? You should consider upgrading to a more recent version of Node.js instead), but since this is not a bug nor an acceptable feature request, I'm going to close this. Don't hesitate to ask more questions if have any though :)

**Comment by 0xdevalias** [comment]
I definitely wasn't asking for nor expecting support to be added for Node 12.x

I just wanted it documented somewhere which version it actually worked on, so I could make use of it in projects that are currently still stuck on 12.x

**Comment by aduh95** [comment]
If you search in the git history, you'll find that the first CI implementation was testing on Node.js 14.x only: https://github.com/nodejs/corepack/commit/4843cb855c1f5dca6c5221f50a5ac30056a9faba

So reasonably you shouldn't expect to be able to run Corepack on anything older. That being said, I used to run Corepack on a project on mine that was still supporting Node.js 12.x and found that Corepack v0.10.0 was the only version that would work.

```yaml
      - name: Install Corepack v0.10.0
        if: matrix.node-version == '12.x'
        # More recent versions of Corepack are not compatible with Node.js 12.x.
        run: npm install -f -g corepack@0.10.0
```

**Comment by 0xdevalias** [comment]
> and found that Corepack v0.10.0 was the only version that would work.

Yup, that's what I found in [this comment](https://github.com/nodejs/corepack/issues/240#issuecomment-1437688569) as well; which answered my question and solved my need.
