### ISSUE TITLE
What does it mean to enable Yarn 3.x "globally"?

### ISSUE THREAD

**Issue by pastelmind** [nodejs/corepack#248]
Hi. This is a question, not a bug report, so feel free to move the discussion elsewhere as needed.

As far as I know, the only version of Yarn meant to be installed globally is the "legacy" [v1.x line](https://github.com/yarnpkg/yarn). Versions 2 and beyond ([berry](https://github.com/yarnpkg/berry)) are meant to be installed separately for each repository under the `.yarn/releases/` subdirectory.

However, when I run `corepack prepare --activate yarn@stable`, it appears to activate Yarn 3.x _globally_.

```console
$ corepack prepare --activate yarn@stable
Preparing yarn@stable for immediate activation...
$ yarn --version
3.5.0
```

Note that the above was executed outside any project directory, so there is no "local copy" anywhere.

Am I missing something? Or does this mean that Yarn Berry can be installed globally (i.e. no local copy needed) in conjunction with Corepack?

Edit: This has practical implications. For example, if I "globally" install Yarn 3.x via `corepack prepare`, the `yarn global add` command is no longer usable since it was removed in Berry. So it does affect some workflows that rely on globally installed packages (whether this is an acceptable practice is another matter).

**Comment by arcanis** [comment]
> Or does this mean that Yarn Berry can be installed globally (i.e. no local copy needed) in conjunction with Corepack?

It can, but it's not recommended in the Yarn install guide. In some cases it's still acceptable though (for example with Docker images where you only have to deal with a single modern project).

**Comment by pastelmind** [comment]
Thanks. In which case I feel we should not recommend updating Yarn via `corepack prepare --activate yarn@stable` as it would install Yarn Berry globally. Would you recommend an alternate method for keeping the legacy, global version of Yarn up to date?

**Comment by arcanis** [comment]
You can pin the install to 1.x:

```
corepack prepare --activate yarn@1.x
```

**Comment by nphmuller** [comment]
When you follow the official installation steps here yarn 3 gets installed globally. Took me a while to realise that corepack installed version 3 globally. Mainly because it's part of the official installation instructions.

https://yarnpkg.com/getting-started/install#updating-the-global-yarn-version

**Comment by nphmuller** [comment]
Also created an issue in the yarn website repository: https://github.com/yarnpkg/website/issues/1193

**Comment by aduh95** [comment]
I think the question was answered, and the Yarn project has since updated its documentation AFAICT. Closing for now, let me know if I missed something.
