### ISSUE TITLE
Document how long an old version is cached

### ISSUE THREAD

**Issue by ST-DDT** [nodejs/corepack#255]
From the readme:

> If the local project is configured for the package manager you're using, Corepack will silently download and cache the latest compatible version.

But cache for how long?
A new package manager version is released every few days and e.g. pnpm takes ~15MB each.
That will eventually cause my laptop disk to fill up with old garbage.
I know the same is true for the pnpm node package cache, but at least that is somewhat easier to find since it is in my home directory.
IMO versions that haven't been used for 60 days can be removed.

As an alternative please add a "cleanup"/cache-purge command to remove old versions.

**Comment by arcanis** [comment]
> But cache for how long?

Currently, until you manually remove them.

> As an alternative please add a "cleanup"/cache-purge command to remove old versions.

That's a good idea, if you're interested to implement it. No need for "60 days" logic, it can just remove them all, since they'll be refetched anyway once needed.

**Comment by styfle** [comment]
See the related issue:

- https://github.com/nodejs/corepack/issues/114

**Comment by ST-DDT** [comment]
Closing in favor of #114
