### ISSUE TITLE
Add GitHub Action for `lint`

### ISSUE THREAD

**Issue by SpencerKaiser** [nodejs/corepack#260]
When making a pull request, listing should be considered and branch protection should be enabled to require a pass from the lint action before a PR can be merged. 

Note: there are quite a few files in the repo that need to be updated with `yarn lint:fix` before this can be turned on without creating new failures

**Comment by merceyz** [comment]
It's already enabled and checked in https://github.com/nodejs/corepack/blob/f539ae22e6c9f044576bc00f91cdd957de9ac8bc/.github/workflows/ci.yml#L41-L42

**Comment by SpencerKaiser** [comment]
Ah... so it just not reporting for my PR? #259

**Comment by merceyz** [comment]
> 1 workflow awaiting approval
This workflow requires approval from a maintainer

Someone needs to approve it first.

**Comment by SpencerKaiser** [comment]
Oof I missed that... welp, my bad!
