### ISSUE TITLE
Error running corepack enable

### ISSUE THREAD

**Issue by Wonderer11** [nodejs/corepack#271]
Internal Error: EPERM: operation not permitted, open 'C:\Program Files\nodejs\pnpm'
Error: EPERM: operation not permitted, open 'C:\Program Files\nodejs\pnpm'

Can anyone tell how to permit operation?

**Comment by gitlocaluser** [comment]
Same and I'm on a fresh install on Windows running the cmd in a cmd prompt as admin and it's failing

**Comment by rotu** [comment]
I *am* able to install on Windows 11 from an admin command prompt or PowerShell prompt. Also from a normal prompt elevated using `gsudo` (which is what I usually do).

What's your `node --version` and `corepack --version`?

**Comment by Wonderer11** [comment]
I am not sure, I uninstall and download the pack again and input all command prompt I fond. Although I still don't understand what make it work, it works now finally.

**Comment by talhameer** [comment]
I faced the same error, I opened the terminal as administrator and ran the command `corepack enable`, and now it works.
