### ISSUE TITLE
RFC: New command names (and alias the old ones)

### ISSUE THREAD

**Issue by arcanis** [nodejs/corepack#274]
I think the current command names are at odds with what most people would expect. What do you think about rewording them to be closer from what package managers' interfaces look like? The old commands would still work, but wouldn't be displayed in `--help` (or perhaps marked as deprecated in the documentation).

- `corepack prepare foo@1.2.3` -> `corepack install -g foo@1.2.3`
- `corepack prepare foo@1.2.3 --activate` -> `corepack use -g foo@1.2.3`

- `corepack hydrate path/to/archive.gz` -> `corepack install -g path/to/archive.gz`
- `corepack hydrate path/to/archive.gz --activate` -> `corepack use -g path/to/archive.gz`

- `corepack prepare -o ...` -> `corepack pack -g`

Along with new commands:

- `corepack use foo@1.2.3` -> Add the `packageManager` field to the `package.json` file
- `corepack remove -g foo` -> Removes all versions from `foo` from the cache
- `corepack up foo` -> Download the latest version from the registry and automatically use it
- `corepack info foo` -> List all versions currently in the cache (and the latest one from the remote)

**Comment by ljharb** [comment]
`corepack remove foo` suggests uninstall to me; any reason not to nest all cache commands under `corepack cache`? eg `corepack cache remove foo`

**Comment by arcanis** [comment]
I forgot to add the `-g` flag to `remove`, would that clarifies the intent? You may notice I also listed it as mandatory flag to `corepack install` to convey that it mutates the system, not the project. A command namespace like `cache` would be a possible alternative, but I'm worried most users would have troubles remembering it vs `-g`, which is very well known.

**Comment by ljharb** [comment]
that still suggests a global uninstall to me, because there's more than one bucket of things that are mutated in the system - the global installs, the cache, config, and corepack itself, to name a few.

**Comment by styfle** [comment]
> corepack use foo@1.2.3 -> Add the packageManager field to the package.json file

I would prefer `corepack add foo@1.2.3` to add/update the `packageManager` field in package.json

**Comment by arcanis** [comment]
> I would prefer `corepack add foo@1.2.3` to add/update the `packageManager` field in package.json

I don't have a strong opinion on this; fwiw I used `corepack use` since adding a package manager would also remove one, which is different from package managers where adding a dependency doesn't mutate the others.

> that still suggests a global uninstall to me, because there's more than one bucket of things that are mutated in the system - the global installs, the cache, config, and corepack itself, to name a few.

Fair enough - `corepack cache clean` then? Both npm and Yarn implement it (not pnpm though).

**Comment by ljharb** [comment]
Makes sense to me.

**Comment by styfle** [comment]
> adding a package manager would also remove one, which is different from package managers where adding a dependency doesn't mutate the others.

It mutates for me. If I do `pnpm add typescript@4` it installs version 4. Then if I run `pnpm add typescript@5`, it upgrades from version 4 to version 5.

That being said, I think your original `use` proposal is better because it works nicely with the `-g` option to mean global machine vs omitting to mean local project. Its also is familiar to those using `nvm` or `fnm`. You convinced me, `use` is better 😇

**Comment by rotu** [comment]
These need to be compatible both ways. Right now, `corepack use` shows an error message on corepack 0.18.0.

It's fine to introduce new commands or new aliases for old commands, but for new commands to be useful, there needs to be a low-friction path to start using them.

I'm thinking one (or both of):
- `corepack enable` should do a self-update of corepack
- unrecognized commands should show some help text about how to update corepack

**Comment by aduh95** [comment]
Fixed by https://github.com/nodejs/corepack/pull/291

**Comment by wyckster** [comment]
Does `use` also `install`? Can anyone confirm that where I was previously using `corepack prepare yarn@stable --activate` I should now be using just the single command: `corepack use -g yarn@stable`?

Or will it be required to do it in two commands: first `corepack install -g yarn@stable` and then `corepack use -g yarn@stable` in a separate command?
