### ISSUE TITLE
Multiple `corepack install` commands presented confusingly.

### ISSUE THREAD

**Issue by rotu** [nodejs/corepack#299]
The help text for `corepack install` is confusing.

---

`corepack --help`

> ━━━ Corepack - 0.20.0 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> ⋮
>   corepack install
>     Install the package manager configured in the local project
> 
>   corepack install <-g,--global> [--all] [--cache-only] ...
>     Install package managers on the system
> ⋮

Note the angle bracket `<...>` syntax and alternative spelling of the `--global` argument, which I think should be omitted from the overview for clarity.

---

`corepack install --help`

> Multiple commands match your selection:
> 
>   0. corepack install <-g,--global> [--all] [--cache-only] ...
>   1. corepack install
> 
> Run again with -h=<index> to see the longer details of any of those commands.

This should show *at least* the summary from `corepack --help`.

---

`corepack install -h=0`

> Install package managers on the system
> 
> ━━━ Usage ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> 
> $ corepack install <-g,--global> ...
> 
> ━━━ Options ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> 
>   --all           If true, all available default package managers will be installed
>   --cache-only    If true, the package managers will only be cached, not set as new defaults
> 
> ━━━ Details ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> 
> Download the selected package managers and install them on the system.
> 
> Package managers thus installed will be configured as the new default when 
> calling their respective binaries outside of projects defining the 
> 'packageManager' field.
> 
> ━━━ Examples ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> 
> Install the latest version of Yarn 1.x and make it globally available
>   $ corepack install -g yarn@^1
> 
> Install the latest version of all available package managers, and make them globally available
>   $ corepack install -g --all

---

`corepack install -h=1`

> Install the package manager configured in the local project
> 
> ━━━ Usage ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> 
> $ corepack install
> 
> ━━━ Details ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> 
> Download and install the package manager configured in the local project. This 
> command doesn't change the global version used when running the package manager 
> from outside the project (use the `-g,--global` flag if you wish to do this).
> 
> ━━━ Examples ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> 
> Install the project's package manager in the cache
>   $ corepack install

The wording here differs unnecessarily "Download the selected package managers and install" versus "Download and install the package manager".

**Comment by arcanis** [comment]
Most of those are related to the CLI framework and not configurable. The wording in your last point is something we can change, but I suggest opening a PR with the changes you suggest if you feel strongly about it - as is, I don't feel like it's worth keeping an open issue.
