### ISSUE TITLE
corepack prepare pnpm@8.9.0 -activate encountered problems;

### ISSUE THREAD

**Issue by Dingzhaocheng** [nodejs/corepack#317]
Current environment: node 20.8.0;
System: Linux version 5.15.0-75-generic (buildd@lcy02-amd64-101) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) # 82~20.04.1-Ubuntu

<img width="898" alt="截屏2023-10-12 14 46 52" src="https://github.com/nodejs/corepack/assets/38446493/825fcf94-eda2-4711-9703-b348ecaba98d">

**Comment by aduh95** [comment]
Did you check out https://github.com/nodejs/corepack#troubleshooting as suggested by the error message?

**Comment by Dingzhaocheng** [comment]
> 您是否按照错误消息的建议查看了[https://github.com/nodejs/corepack#troubleshooting ？](https://github.com/nodejs/corepack#troubleshooting)

I read it, but I'm not sure if it has anything to do with that, and could you please give me a little hint

**Comment by aduh95** [comment]
It could be that the network you’re on is limiting or blocking the access to nodejs.org (maybe your employer, your government, or your network admin has some kind of filter). You need to give to Corepack a proxy to use so it can reach the remote repository.

**Comment by Dingzhaocheng** [comment]
> 可能是您所在的网络限制或阻止了对 nodejs.org 的访问（也许您的雇主、您的政府或您的网络管理员有某种过滤器）。您需要为 Corepack 提供一个代理来使用，以便它可以到达远程存储库。

Maybe that's the problem. It's suddenly okay again.extremely grateful
