### ISSUE TITLE
use COREPACK_NPM_REGISTRY but throw Internal Error: Server answered with HTTP 301 when performing the request 

### ISSUE THREAD

**Issue by wind4gis** [nodejs/corepack#336]
I run `COREPACK_NPM_REGISTRY=https://registry.npm.taobao.org corepack prepare pnpm@latest-8 --activate`
but it throw the error `Internal Error: Server answered with HTTP 301 when performing the request to https://registry.npm.taobao.org/pnpm; for troubleshooting help, see https://github.com/nodejs/corepack#troubleshooting`

**Comment by guibwl** [comment]
Taobao registry will redirect and return with 302;

![image](https://github.com/nodejs/corepack/assets/26807750/29bb835e-9e62-4b17-a5f3-75dff1b53697)

but will cause corepack error；

```shell
 [exec] Internal Error: Server answered with HTTP 302

     [exec]     at ClientRequest.<anonymous> (/home/ndp-soft/node-v16.20.1-linux-x64/lib/node_modules/corepack/dist/corepack.js:43949:23)

     [exec]     at Object.onceWrapper (node:events:628:26)

     [exec]     at ClientRequest.emit (node:events:513:28)

     [exec]     at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)

     [exec]     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)

     [exec]     at TLSSocket.socketOnData (node:_http_client:534:22)

     [exec]     at TLSSocket.emit (node:events:513:28)

     [exec]     at addChunk (node:internal/streams/readable:315:12)

     [exec]     at readableAddChunk (node:internal/streams/readable:289:9)

     [exec]     at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
```

Source code in here:
https://github.com/nodejs/corepack/blob/b7aa57644c490f8700834721ab0a70d093264b22/sources/httpUtils.ts#L18C68-L18C68
![image](https://github.com/nodejs/corepack/assets/26807750/f704d997-0f35-47fb-9499-ce39e112ad01)

I think return 302 should be allowed? Can anyone change this logic?

**Comment by arcanis** [comment]
Corepack doesn't support redirections. We welcome PRs.

**Comment by guibwl** [comment]
> Corepack doesn't support redirections. We welcome PRs.

hi, I made a PR for support redirections.
https://github.com/nodejs/corepack/pull/341
