### ISSUE TITLE
`corepack use` fails with ENOENT: no such file or directory, open '/app/package.json'

### ISSUE THREAD

**Issue by styfle** [nodejs/corepack#347]
When a package.json file is missing, `corepack use` fails with ENOENT.

I think it would be great if corepack could create the package.json file when its missing.

It would avoid the need to call `npm init -y`, `yarn init -y`, or `pnpm init` in some cases.

**Comment by aduh95** [comment]
What do you think should be the behavior? Should Corepack call `<pkg-manager> init` in such case? Or just create a `package.json` with only the `"packageManager"` field?

**Comment by styfle** [comment]
The second option - create package.json directly

**Comment by styfle** [comment]
@aduh95 Thanks for the quick fix! 🎉
