### ISSUE TITLE
Loosen `packageManager` field to support any package on npm

### ISSUE THREAD

**Issue by styfle** [nodejs/corepack#354]
Could we consider changing the behavior of Corepack to loosen the definition of the `packageManager` field? 

That way you could [define any npm package name](https://twitter.com/styfle/status/1745819897966301258) in the `packageManager` field and Corepack would fetch from the npm registry if its not found in the hardcoded known package manager list.

### Examples

* https://github.com/nodejs/corepack/issues/295
* https://github.com/nodejs/corepack/issues/331

### Pros

1. Less gatekeeping because a new package manager can be used immediately without changing Corepack's src code.
2. A little more intuitive since the `packageManager` field feels a lot more like `dependencies`

### Cons

1. We might lose the ability to catch typos since today those are caught with `Usage Error: Unsupported package manager specification`.
2. We might loose the ability to catch wrong package manager install with `Usage Error: This project is configured to use`

I think number 1 is okay but number 2 sounds problematic. Perhaps number 2 still requires a PR to Corepack.

### Related 
- Related to https://github.com/nodejs/node/issues/50963

**Comment by arcanis** [comment]
Maybe, with a caveat. Corepack isn't intended to be a package manager. As a result, any tool it installs must not have any dependency.

> We might lose the ability to catch typos since today those are caught with `Usage Error: Unsupported package manager specification.`

If we do this, I believe "generic" packages should be targeted with a dedicated syntax. Something like:

```json
{
    "packageManager": "pkg:cnpm@x.y.z"
}
```

Otherwise there'll be a problem with Yarn, which currently retrieves the package from one of two different sources depending on the version (even if we switched Yarn Modern to npm releases, it'd still come from two different packages; we don't want to publish modern releases on the `yarn` package so as not to break any current user).

**Comment by styfle** [comment]
> Maybe, with a caveat. Corepack isn't intended to be a package manager. As a result, any tool it installs must not have any dependency.

Oh thats good to know. Looks like bun has 0 deps but cnpm has 11. 

> Otherwise there'll be a problem with Yarn, which currently retrieves the package from one of two different sources depending on the version

My suggestion is to not change the behavior of Yarn/pnpm/npm as it is today. Only to open the door to other package managers. Basically, check [`config.json`](https://github.com/nodejs/corepack/blob/main/config.json), and fallback if there is no match.

**Comment by aduh95** [comment]
Maybe we could accept either a bare specifier – in which case Corepack checks the `config.json` to download the right archive – or a URL. I think the URL should address the issue at hand (anyone can use their package manager, or even easily fork an existing package manager) without forcing them to store it on any specific repository. Not sure how Corepack would know what name to use for the binary though 🤔

**Comment by styfle** [comment]
> Not sure how Corepack would know what name to use for the binary though

Since the url is going to point to a file download, how about using the `Content-Disposition` header?

For example, `bun` could be:

```
Content-Disposition: attachment; filename="bun"
```

Would this work with caching? I guess the url should have the version number in it and corepack could cache by url string?

**Comment by arcanis** [comment]
Since the `packageManager` field is only read when a shim is called, how would Corepack know that a specific shim needs to be installed in the PATH in the first place? For instance, what would make `bun` globally available so that `bun install` would read the `packageManager` field and install `bun` from the url configured there?

**Comment by aduh95** [comment]
> Since the `packageManager` field is only read when a shim is called, how would Corepack know that a specific shim needs to be installed in the PATH in the first place? For instance, what would make `bun` globally available so that `bun install` would read the `packageManager` field and install `bun` from the url configured there?

The way I imagine that would be that those folks would do `corepack enable bun`, and that would create the jumper script. That doesn't seem to be very different from what we have now.

**Comment by aduh95** [comment]
Actually we could have both the "binary name" and the URL:

```json
{
  "packageManager": "aduh95-special-pm@http://example.com/archive.tgz#sha224.xxxxxxxxxxx"
}
```

If someone tries to run `corepack yarn install`, Corepack would be able to throw an error, and if you run `corepack aduh95-special-pm install`, it would "just work" – or if you have an `aduh95-special-pm` binary in your path installed by Corepack.

That got me thinking, should we support the following:

```json
{
  "packageManager": "pnpm@http://example.com/archive.tgz#sha224.xxxxxxxxxxx"
}
```

And I think by default Corepack should refuse to do so, so folks by default would run official binaries of package managers that are in `config.json`, but we should have an env variable to allow to use unofficial ones.

**Comment by nilson-aguiar** [comment]
I'm going through a problem that relates to this one, my ci is not  downloading yarn from a private registry even if I set the `COREPACK_NPM_REGISTRY`, also mentioned here #296 

```
➜ docker run --rm -it -v "${PWD}/hosts":/etc/hosts -v "${PWD}":/app renovate/renovate:latest bash

ubuntu@1c986875550f:/usr/src/app$ cd /app
ubuntu@1c986875550f:/app$ yarn
Internal Error: Error when performing the request to https://registry.npmjs.org/yarn; for troubleshooting help, see https://github.com/nodejs/corepack#troubleshooting
    at ClientRequest.<anonymous> (/opt/containerbase/tools/corepack/0.24.0/node_modules/corepack/dist/lib/corepack.cjs:42208:16)
    at ClientRequest.emit (node:events:517:28)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
ubuntu@1c986875550f:/app$ 
ubuntu@1c986875550f:/app$ export COREPACK_NPM_REGISTRY="https://my-private-repo/"
ubuntu@1c986875550f:/app$ yarn
Internal Error: Error when performing the request to https://repo.yarnpkg.com/3.1.0/packages/yarnpkg-cli/bin/yarn.js; for troubleshooting help, see https://github.com/nodejs/corepack#troubleshooting
    at ClientRequest.<anonymous> (/opt/containerbase/tools/corepack/0.24.0/node_modules/corepack/dist/lib/corepack.cjs:42208:16)
    at ClientRequest.emit (node:events:517:28)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
ubuntu@1c986875550f:/app$ 
```

my CI pipeline has no access to external networks so I simulated the problem with a hosts file

hosts file:

```
127.0.0.1       localhost
127.0.0.1       registry.npmjs.org
127.0.0.1       yarnpkg.com
```

so being able to set a url for it could be an option indeed to bypass the problem, but would be nicer to configure it through env variables

**Comment by merceyz** [comment]
That doesn't seem related, please open a separate issue.

**Comment by aduh95** [comment]
Worth noting that, at that time, none of the Corepack commands are "interactive", meaning you type the command, Corepack will execute it without requiring any additional step from the user. The suggested workflow breaks this, which may or may not be worth it.
We might find the following to be more fitted:

```console
$ corepack use pkgmgr
Usage Error: Invalid package manager specification in CLI arguments. Consider adding the `--from-npm` flag if you meant to use the npm package `pkgmgr` as your package manager
$ corepack use pkgmgr --from-npm
$ cat package.json
{ "packageManager": "pkgmgr@https://registry.npmjs.com/pkgmgr/-/pkgmgr-3.0.0.tgz#sha1.xxxxxxxx" }
$ pkgmgr
Project installed
```

**Comment by mhdawson** [comment]
I liked the what @arcanis had in https://github.com/nodejs/corepack/issues/354#issuecomment-1895447883 because it makes it clear what is going to be installed, where from, and the user needs to confirm that they want it installed.
