### ISSUE TITLE
Option to disable SSL verification

### ISSUE THREAD

**Issue by mirayashi** [nodejs/corepack#355]
We are using a custom NPM registry, and the SSL cert is self-signed so we get `Error: self-signed certificate in certificate chain`. It would be nice to add an environment variable like `COREPACK_SSL_VERIFY` that we could set to false in order to avoid such errors.

**Comment by merceyz** [comment]
That error is thrown by Node.js, you should be able to set `NODE_TLS_REJECT_UNAUTHORIZED=0` to ignore it.

**Comment by mirayashi** [comment]
> That error is thrown by Node.js, you should be able to set `NODE_TLS_REJECT_UNAUTHORIZED=0` to ignore it.

This worked well, thank you!
