### ISSUE TITLE
v0.25.0 crashes with ENOENT on fresh install

### ISSUE THREAD

**Issue by merceyz** [nodejs/corepack#379]
In a fresh docker container running Corepack crashes with ENOENT

```console
$ docker run --rm -it node:20.11.1 bash -c "npm install -g corepack@0.25.0 && corepack yarn -v"
Internal Error: ENOENT: no such file or directory, open '/root/.cache/node/corepack/lastKnownGood.json'
Error: ENOENT: no such file or directory, open '/root/.cache/node/corepack/lastKnownGood.json'
```

Git bisect points to https://github.com/nodejs/corepack/pull/364.

**Comment by devj3ns** [comment]
Same issue here. Maybe related to [this](https://github.com/nodejs/corepack/pull/364) change in v0.25.0 ?

**Comment by merceyz** [comment]
Git bisect points to https://github.com/nodejs/corepack/pull/373.

**Comment by merceyz** [comment]
Git bisect points to https://github.com/nodejs/corepack/pull/373.

**Comment by half0wl** [comment]
Same issue here on [railway.app](https://railway.app/) -- we're seeing a lot of builds utilizing corepack fail due to this.

Our current workaround is to install the last known good release (`0.24.1`):
```sh
npm install -g corepack@0.24.1
```

**Comment by nikolalsvk** [comment]
I'm using railway.app with nixpacks and the fix is to create a `nixpacks.toml` with this:

```
[phases.install]
cmds = ["npm install -g corepack@0.24.1 && corepack enable", "pnpm i --frozen-lockfile"]
dependsOn = ["setup"]
```

I'm using `pnpm i --frozen-lockfile` but you can replace it with the command of your choice.

**Comment by aduh95** [comment]
I have a potential fix: https://github.com/nodejs/corepack/pull/382
If someone could try it out and confirm if it solves the issue, that'd be great.

**Comment by ajw725** [comment]
we ran into this as well. running `corepack install --global <yarn-version>` fixes the issue, but we have to run that separately for each user that needs to use yarn.

**Comment by ntucker** [comment]
Thanks for the quick fix aduh95! I'm wondering since this is breaking many peoples CI - when is the plan to release this? I can't do a workaround for my usage of https://docs.renovatebot.com/ as it is a third party tool that depends on this working.

**Comment by aduh95** [comment]
v0.25.2 is out with the fix. Let us know if you're still issues.

**Comment by Elantest** [comment]
Thanks, it works as expected !

**Comment by secustor** [comment]
> Thanks for the quick fix aduh95! I'm wondering since this is breaking many peoples CI - when is the plan to release this? I can't do a workaround for my usage of https://docs.renovatebot.com/ as it is a third party tool that depends on this working.

You can pin corepack and tools in such situations https://github.com/renovatebot/renovate/discussions/27465

**Comment by chenrui333** [comment]
Works on the brew side. Thanks for the quick fix!

- https://github.com/Homebrew/homebrew-core/pull/163328
