### ISSUE TITLE
Don't change file if not necessary

### ISSUE THREAD

**Issue by cdtut** [nodejs/corepack#422]
`corepack install --global` always writes to file. Don't touch file if not necessary including if there is not change to a version. And output should be different and say `yarn@version already installed` not `Installing yarn@version...`.

**Comment by aduh95** [comment]
Can you clarify what you mean by that? Any chance you could include a list of commands that would show the problem?

**Comment by cdtut** [comment]
`corepack install --global yarn` adds yarn to `~/.cache/node/corepack/lastKnownGood.json`. Do it again and same file is written even if no change.

And output still says `Installing` but was already installed.
