### ISSUE TITLE
Silent option on corepack

### ISSUE THREAD

**Issue by Qwarctick** [nodejs/corepack#452]
Hello,

I use corepack with yarn in a docker image. But when I run an interactive command with my container, I get the following message: 

``` bash
Corepack is about to download https://repo.yarnpkg.com/4.1.0/packages/yarnpkg-cli/bin/yarn.js.
Do you want to continue? [Y/n]
```
Is it possible to disable this behavior? I know that if I run the container without TTY, it disables the interactive question, but it's not possible in my context.

**Comment by merceyz** [comment]
Yes, you can use `COREPACK_ENABLE_DOWNLOAD_PROMPT=0`, see https://github.com/nodejs/corepack/blob/467216281e1719a739d0eeea370b335adfb37b8d/README.md#environment-variables.

**Comment by trivikr** [comment]
This issue can be closed, as `COREPACK_ENABLE_DOWNLOAD_PROMPT=0` enables the silent option requested.
