### ISSUE TITLE
`corepack install --global pnpm@8.x` doesn't work

### ISSUE THREAD

**Issue by bestickley** [nodejs/corepack#472]
Hi, I'm expecting `corepack install --global pnpm@8.x` to update my global version of pnpm but it doesn't work. See below output from CLI:

```bash
node --version
v20.11.1
pnpm --version
8.2.0
corepack install --global pnpm@8.x
Installing pnpm@8.15.8...
pnpm --version
8.2.0
```

I'd expect `pnpm --version` at the end to output 8.15.8

**Comment by aduh95** [comment]
Can you try running `corepack pnpm --version`

**Comment by bestickley** [comment]
```
corepack --version
0.23.0
```
Sorry, I just found my issue. I was running this in a directory with a package that unknown to me, has `packageManager: pnpm@8.2.0`. Sorry for the false alarm! Appreciate quick response.
