### ISSUE TITLE
prepare and enable command is not documented

### ISSUE THREAD

**Issue by coryzibell** [nodejs/corepack#477]
`corepack prepare package_manager@version`

and

`corepack prepare package_manager@version --activate`

are both valid commands, seeing this output with the latest npm:

```
➜  ~ corepack prepare yarn@stable
Preparing yarn@stable...
➜  ~ corepack prepare yarn@stable --activate
Preparing yarn@stable for immediate activation...
```

However they are not mentioned in the README at all. How do they differ from `corepack enable` or `corepack install -g` or `corepack use`?

I'm happy to update the README with a PR, but I want to ensure the information is accurate and up to date

**Comment by aduh95** [comment]
The documentation was removed in https://github.com/nodejs/corepack/pull/291, the old commands still work to not break users, but there are better alternatives now.

**Comment by coryzibell** [comment]
Ah that makes sense, thanks!
