### ISSUE TITLE
Specify Version with `corepack enable` when using pnpm

### ISSUE THREAD

**Issue by ScottAwesome** [nodejs/corepack#49]
Corepack version: 0.9.0

Expected behavior: when using `corepack enable` expect to be able to tell it which version should be enabled, much like `corepack use`.

Actual behavior: `corepack enable` does not automatically download the latest version of the package manager in question by default. Which pnpm, it downloads `6.11.0` instead of `6.14.3` (latest as of the date of this post, 8/28/2021).  It does not support the version string like `corepack use` does, e.g. `corepack enable pnpm@latest` is not supported.

This is not applicable to yarn, since yarn detects the version based on the `.yarn` directory and what version has been registered there.

EDIT: I know that you can do the following steps (which may be somewhat redudant here) to achieve this, I think it would be more straightforward (this was not obvious to me at least) if this was done by `corepack enable` in this scenario.

I was able to get it to use the latest version by doing the following:

- run `corepack prepare pnpm@6.14.3 -o ./`
- Then running `corepack hydrate ./corepack.tgz --activate`
- Finally, running `corepack enable pnpm`

The steps above resulted in the latest pnpm being available.

If this is in fact the desired flow for using arbitrary versions, I'm happy to help document this flow

**Comment by merceyz** [comment]
`corepack enable` is just supposed to enable the shims, not set specific versions. To change the global version you can run 
```
corepack prepare pnpm@6.14.3 --activate
```
though keep in mind `corepack` is meant to be used with a `packageManager` field in `package.json`
