### ISSUE TITLE
When using "COREPACK_NPM_REGISTRY", corepack still fetches pnpm from npmjs.org

### ISSUE THREAD

**Issue by leo91000** [nodejs/corepack#498]
I have my packageManger field set to "pnpm@9.0.2"

When using `COREPACK_NPM_REGISTRY` environment variable, corepack fetch succesfully metadata for the given package manager using the provided registry url.

However it seems that the metadata provided by the private package manager returns a `tarball` located on npmjs.org :

![image](https://github.com/nodejs/corepack/assets/1354510/27035d11-2a7f-47a8-a0dd-ba26ed7c6a78)

As a result, it downloads pnpm from npmjs.org

I am not sure if this is an issue with the private package manager of my company, or if this is some problem with how corepack interpret this.

**Comment by aduh95** [comment]
What version of Corepack are you using?
