### ISSUE TITLE
Create the tag distributed with Node.js v16.9.0

### ISSUE THREAD

**Issue by navarroaxel** [nodejs/corepack#50]
Now Node.js v16.9.0 includes `corepack` v0.9.0, please tag that version in the repository.

**Comment by arcanis** [comment]
Tagged as `corepack/0.9.0`

**Comment by navarroaxel** [comment]
Thanks @arcanis for the quick response!
But I think the tag should be named just `v0.9.0` to be consistent with another project, also now the downloaded `.tar.gz` of the tag is named `corepack-corepack-0.9.0.tar.gz` with a folder inside named `corepack-corepack-0.9.0` :confused:
