### ISSUE TITLE
[Question]How the 'COREPACK_ENABLE_UNSAFE_CUSTOM_URLS=1` use ?

### ISSUE THREAD

**Issue by uwang** [nodejs/corepack#508]
The document mentioned `COREPACK_ENABLE_UNSAFE_CUSTOM_URLS=1` can use custom URL to download package manager. But not make detailed description.

I try that:

```shell
COREPACK_ENABLE_UNSAFE_CUSTOM_URLS=1 corepack install https://repo.yarnpkg.com/4.1.1/packages/yarnpkg-cli/bin/yarn.js
``` 
or
```shell
COREPACK_ENABLE_UNSAFE_CUSTOM_URLS=1 corepack prepare https://repo.yarnpkg.com/4.1.1/packages/yarnpkg-cli/bin/yarn.js
```

Noting worked. I have no idea. Thanks

**Comment by aduh95** [comment]
Try the following

```sh
COREPACK_ENABLE_UNSAFE_CUSTOM_URLS=1 corepack yarn@http://example.com --version
```

You can also put that URL as `"packageManager"` in a `package.json`.

**Comment by uwang** [comment]
I got it. Thanks very much.
