### ISSUE TITLE
corepack documentation: ??= nullish-coalescing-assignment not supported in node 14

### ISSUE THREAD

**Issue by mikebridge** [nodejs/corepack#536]
Running `corepack` for the first time in node 14.17.0 gives me this error:

```
$ corepack
/path/to/.nvm/versions/node/v14.17.0/lib/node_modules/corepack/dist/corepack.js:2
process.env.COREPACK_ENABLE_DOWNLOAD_PROMPT??='0';
                                           ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:984:16)
    at Module._compile (internal/modules/cjs/loader.js:1032:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

It looks like the [??=](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_assignment) operator is [not supported in node 14](https://node.green/#ES2021-features-Logical-Assignment-----basic-support).

It might be worth adding minimum requirements to the installation documentation: https://yarnpkg.com/corepack#installation. 
(It seems to indicate that it would work with 14.19 but I wonder if that's still the case)

**Comment by aduh95** [comment]
> It might be worth adding minimum requirements to the installation documentation: https://yarnpkg.com/corepack#installation.

That's the Yarn website, we do not control that (it's maintained by the Yarn project).

Supported versions of Node.js is documented in https://github.com/nodejs/corepack/blob/06e587218968c614371b187cc5b193a64273dbf4/package.json#L13. If you want to use Node.js 14.x, you'd need to use an older version of Corepack (or really, you should update your version of Node.js to a supported one, Node.js 14.x has been EOL for more than a year now).

Closing for now, let me know if you think we should take some action still.
