### ISSUE TITLE
So how do I configure a project exactly ?

### ISSUE THREAD

**Issue by GrosSacASac** [nodejs/corepack#54]
The readme leaves me clueless, the https://github.com/nodejs/corepack/blob/main/DESIGN.md says it is "engines": {
    "pm": "yarn@^2.0.0"
  } and the node doc says {
  "packageManager": "<package manager name>@<version>"
}
so which one is it ?

**Comment by arcanis** [comment]
`packageManager`. I'll update the readme to reference that. Note that it must be an exact version, not a range.
