### ISSUE TITLE
feature request: replace npm with npm v6 when the current folder contains package-lock.json with lock v1

### ISSUE THREAD

**Issue by Jack-Works** [nodejs/corepack#65]
npm v7 and v8 will upgrade the lockfile. that's inconvenient when working on projects you cannot control the upgrade of lockfile.

**Comment by merceyz** [comment]
The package manager to use is controlled by the [`package.json#packageManager`](https://nodejs.org/dist/latest-v16.x/docs/api/packages.html#packagemanager) field so if you want to use a specific version that's what you need to change.

**Comment by ljharb** [comment]
Also, npm supports a `lockfileVersion` config, so you can put `lockfileVersion=1` in `.npmrc`.

**Comment by Jack-Works** [comment]
> The package manager to use is controlled by the [`package.json#packageManager`](https://nodejs.org/dist/latest-v16.x/docs/api/packages.html#packagemanager) field so if you want to use a specific version that's what you need to change.

It's reasonable to me, but IIRC corepack currently don't ship for npm

**Comment by Jack-Works** [comment]
> Also, npm supports a `lockfileVersion` config, so you can put `lockfileVersion=1` in `.npmrc`.

Yeah, if I can edit .npmrc I'd rather upgrade the lock file directly. It's highly likely not possible to change either one when contributing to other OSS.

I use `pnpx -y npm@6 install` as the solution currently.

**Comment by arcanis** [comment]
> > The package manager to use is controlled by the [`package.json#packageManager`](https://nodejs.org/dist/latest-v16.x/docs/api/packages.html#packagemanager) field so if you want to use a specific version that's what you need to change.
> 
> It's reasonable to me, but IIRC corepack currently don't ship for npm

Which prevents from doing other types of version swaps.

The right way to support this will be to enable npm support, which is something in npm's hands.

**Comment by merceyz** [comment]
> corepack currently don't ship for npm

Corepack supports `npm` but it isn't enabled by default, you can explicitly enable it if you want to.
```sh
corepack enable npm
```
