### ISSUE TITLE
Cannot run `pnpm dist-tag react` in a pnpm configured project

### ISSUE THREAD

**Issue by Jack-Works** [nodejs/corepack#68]
`pnpm dist-tag` will delegate the command to `npm dist-tag` and cause an error.

```
pnpm dist-tag react
Usage Error: This project is configured to use pnpm

$ npm ...
```

I suggest making some commands that can be run in any project like `dist-tag` because they do not do anything related to the project.

**Comment by arcanis** [comment]
That's an interesting one, didn't know pnpm delegates commands to npm 🤔 cc @zkochan

**Comment by zkochan** [comment]
Yes, we do currently pass through to npm CLI some of the commands. We might implement them in pnpm in the future but it is not high priority. 

Can we run npm with some option or env variable to skip the check?

**Comment by andreialecu** [comment]
I'd also like some sort of env variable to skip the check. Two examples:

Can't install global packages using npm. Some tools rely on running `ng` directly without the `yarn` prefix. This can be worked around by `cd`ing to some directory where `yarn` isn't set up as the PM.
```
➜ npm install -g @angular/cli                                                           
Usage Error: This project is configured to use yarn

$ npm ...
```

And most importantly, `release-it` delegates to `npm` to publish packages. In a `yarn` project it cannot be used:

![image](https://user-images.githubusercontent.com/697707/168595634-89265b43-6f81-4ba7-959b-55b2c2799620.png)

**Comment by styfle** [comment]
> I'd also like some sort of env variable to skip the check. 

There is one: `COREPACK_ENABLE_STRICT=0`

https://github.com/nodejs/corepack/blob/main/README.md#environment-variables
