### ISSUE TITLE
Prepare the "Last" version?

### ISSUE THREAD

**Issue by hyrious** [nodejs/corepack#72]
The `prepare` command will choose "Known Good Releases" when it is not specified with a version range. Generally npm@7.20.1, pnpm@6.11.0 and yarn@1.22.15. I'm wondering if it can just choose the last version of them. Because Node.js 16 is installed [with npm@8](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V16.md#other-notable-changes), it is quite surprising that `corepack enable` gives me npm@7.

Currently `corepack prepare` requires a full version to work, i.e. `x.y.z`. When I want to upgrade `npm` to 8, I have to ask npm once to get the correct version (`npm view npm` or `npm dist-tag ls npm`, and copy the `latest` field).

So I hope corepack would have `corepack prepare --latest` to just install the latest version, or maybe `corepack upgrade --interactive`.

**Comment by arcanis** [comment]
Indeed, a `--latest` flag would make sense 🤔

**Comment by ljharb** [comment]
Given that npm 7 is EOL, and npm 8 is entirely "known good" versions, it seems like perhaps that should be the default.

**Comment by arcanis** [comment]
Perhaps indeed; there are a few points around this topic:

- The "known good" is currently intended to be fixed per Node release, to mirror how npm is currently distributed. So in this context the `--latest` flag would still be useful (would basically be the safer equivalent of `npm i -g npm`).

- The "know good" versions are currently tracked in [this file](), which is updated manually. I can look to make a GitHub Action that would check daily what are the stable versions, and update it automatically, that seems a good idea to make decrease maintenance burden.

- Note that `corepack enable` will still, by default, not install the npm shims, so the exact versions set as "known good" releases are less important for it than they are for pnpm / Yarn (at least at the moment).

**Comment by ljharb** [comment]
There is no node release line that still ships node 7; they all ship either node 6 or node 8.

**Comment by aduh95** [comment]
I've opened https://github.com/nodejs/corepack/pull/136 which I think should address this issue.
