### ISSUE TITLE
Silent install is unexpected

### ISSUE THREAD

**Issue by styfle** [nodejs/corepack#75]
Here's what I tried:

- Install Node.js 16
- Run `corepack enable`
- Run `pnpm --version`, it prints "6.11.0"
- Run `echo '{ "packageManager": "pnpm@6.24.0" }' > package.json`
- Run `pnpm --version` again, this time it prints "6.24.0"

I think this feature is great!

However, the fact that there is a silent installation that takes 4x longer to run `pnpm --version` is a bit worrisome and unexpected.

I think corepack should print something when its installing a new version so its clear that something is happening in the background. And perhaps even print where its installing to. (Related to #55)

**Comment by arcanis** [comment]
The problem with outputting something is that it'd mess with regular output, which could be a problem for programmatic cases (for instance `yarn workspaces list --json` could break).

There were some ways to alleviate this problem (only print on tty? use stderr?), but I wasn't sure it'd bring enough to the table so I didn't go far in this investigation when I implemented the initial behavior, especially considering that for Corepack to be eventually a feature enabled by default, it needs to be as low-risk as possible in terms of breakages 🤔

**Comment by styfle** [comment]
Perhaps using an environment variable to enable verbose mode?

```sh
export COREPACK_VERBOSE=1
```

I think that users will want to see this information, especially time to install your package manager, in CI.

For example, today there's another step in CI: `npm i -g pnpm` and you can see how long this takes and if it fails.

But with corepack, that information is lost and it might be harder to debug 🤔

**Comment by merceyz** [comment]
> Perhaps using an environment variable to enable verbose mode?

Corepack uses `debug` so you can already see that information if you really want to
```sh
$ echo '{ "packageManager": "pnpm@6.24.0" }' > package.json
$ DEBUG="corepack" pnpm --version
  corepack Installing pnpm@6.24.0 from https://registry.npmjs.org/pnpm/-/pnpm-6.24.0.tgz +0ms
  corepack Install finished +2s
6.24.0
```

**Comment by ljharb** [comment]
or perhaps not implicitly installing by default at all?

**Comment by arcanis** [comment]
Closing since `DEBUG=corepack` answers the question.

**Comment by pcjmfranken** [comment]
You're hijacking user commands, modifying the system runtime even for project-scope operations, and doing the equivalent of a curl pipe without even verifying the downloaded archive hash.

Not asking before doing is annoying, but not even informing the user of this behaviour by default is shady and borderline unethical. 

And heaven forbid this ever comes enabled by default, if it's done in conjunction with a major Node version change, you should be alright to ship a breaking change in command output.
