### ISSUE TITLE
yarn , pnpm  I would like to switch between the two is it possible? 

### ISSUE THREAD

**Issue by frog-o** [nodejs/corepack#77]
I like trying out new. IMHO That is the true test if it works for you.

One of the program I used was yarn  so I had to enable it. 

I would like to now use pnpm in my own project but if I run

>pnpm install --silent

but it gives me 

"Usage Error: This project is configured to use yarn"

It is a brand new project with nothing. I just made it with nestjs framework 
>nest new.

**Comment by arcanis** [comment]
You will have to update your `packageManager` field in your `package.json`.

**Comment by frog-o** [comment]
@arcanis Thankyou ,
I see that is also some what in the documentation. 
 I read it somewhere else also.
 But it was hard for me to find.
I don't Like to spend time looking for stuff  so , I Tried cleaning up your doc to address this .  I hope it is useful.
