### ISSUE TITLE
Step 1

### ISSUE THREAD

**Issue by OpticalDelusion369** [nodejs/corepack#89]
Hello I am obviously brand new to this and I can follow along and I have all the information of what to put in As far as the codes repositories and all that but my problem is I don’t know where to put all that where do we start what do we have to open to input the codes into thank you

**Comment by RDIL** [comment]
A terminal application.

**Comment by OpticalDelusion369** [comment]
🤦‍♀️🙈🙉🙈 ok I need you to keep going .... what's that .... #DontJudgeMePlease 👀

**Comment by RDIL** [comment]
Pretty sure this isn't the right place to ask for support, you will have to find it somewhere else, as I'm not a very good teacher and don't really have time to teach.

**Comment by arcanis** [comment]
Indeed, issue trackers aren't the right place to find people that can provide you general programming help. I'd suggest to find a community dedicated to this.
