### ISSUE TITLE
Repository administration

### ISSUE THREAD

**Issue by arcanis** [nodejs/corepack#90]
I'm working to setup automatic updates & releases on the repository (first step was #88), but I don't have the permissions to manage the repository (in particular I need to add a secret for the npm publish step, and give the permissions for a bot user to bypass the branch protection on scheduled jobs, cf [failed logs](https://github.com/nodejs/corepack/runs/5100500974?check_suite_focus=true)).

What's the process to do this?

cc @jasnell

**Comment by mmarchini** [comment]
https://github.com/nodejs/admin/blob/main/GITHUB_ORG_MANAGEMENT_POLICY.md#github-apps-bot-personal-tokens-and-repository-secrets

**Comment by arcanis** [comment]
Ah perfect, thanks! I read this repo's readme, but didn't notice the other files 😅

**Comment by aduh95** [comment]
I think this issue has been addressed by https://github.com/nodejs/admin/issues/660.
