### ISSUE TITLE
Hardcoded references to registry.npmjs.org

### ISSUE THREAD

**Issue by joaoluispinto** [nodejs/corepack#92]
Code currently hardcodes references to https://registry.npmjs.org, which makes corepack (and yarn) not usable inside a walled corporate network, even though that network might offer a local private repository for npm.

Also, even the DNS resolution of registry.npmjs.org might not be available in the walled scenario, in which case running (for example - and whichever parameter is used) yarn will return a not very informational:

Internal Error: Error when performing the request

This happens at least in the latest 0.10.0 release, with node.js v12.16.1 LTS.

**Comment by aduh95** [comment]
What would be an appropriate workaround? A CLI flag? An env variable? Both?
