### ISSUE TITLE
'corepack prepare' does not read "packageManager" in package.json

### ISSUE THREAD

**Issue by brandon-leapyear** [nodejs/corepack#96]
The [docs](https://github.com/nodejs/corepack#corepack-prepare--nameversion) and [comments](https://github.com/nodejs/corepack/blob/1d41c484800dc043d0c713aba6a4e3bbc0e1ee09/sources/commands/Prepare.ts#L22-L23) indicate that `corepack prepare` should look at the package manager configured in `package.json` and download it, but it currently doesn't.

## Repro
1. `docker run --rm -it --entrypoint sh node:16.11.1-alpine3.14`
2. `echo '{"packageManager": "yarn@3.0.2"}' > package.json`
3. `ls ~/.node` doesn't exist (expected)
4. `corepack prepare`
5. `ls ~/.node` doesn't exist **(unexpected)**
6. `corepack yarn --version` (shows 3.0.2)
7. `ls ~/.node` does exist (expected)

**Comment by kylemh** [comment]
Hey @arcanis 

I think fixing this introduced an issue that's worth resolving. If have the `packageManager` set, but then run a `prepare` command with a specific version listed, the value is silently ignored and the `packageManager` value is adhered to. I think it'd be better for the command to fail with a helpful error or at least provide a logging statement to be less silent about the mistake.

**Comment by kherock** [comment]
@kylemh I don't think this fix has been released yet, unless you have a configuration where you're running corepack from source. Keep in mind that, when defined, `packageManager` is _always_ adhered to when using corepack is being used. To change the package manager version that a project uses, I think you're expected to edit package.json and commit the update.

**Comment by kherock** [comment]
The docs for `corepack <binary name>[@<version>] [... args]` kind of dances around this fact:

> Note that those commands still check whether the local project is configured for the given package manager (ie you won't be able to run `corepack yarn install` on a project where the `packageManager` field references pnpm).

**Comment by kylemh** [comment]
I am installing in CI and using it from source because I'm on Node 14.

What you're saying is totally fair, and I gathered as much... but only after a lot of investigation. There's nothing wrong with the logic, but the CLI logging offers no notice. I guess I'm suggesting that the config "winner" gets an announced in the output of a ran command.
